base_dir: &dir
#  "/home/hpguo/datasets/isic2018/"
  "/home/chensen/msvm-unet-main/dataset/isic2018/"

train_transforms:  &train_transform
  - class: AIIT2TensorPair
  - class: AIITNormalizePair
    mean: 157.561
    std: 26.706
  - class: AIITMinMaxScaling
    out_range: [0., 255.]
  - class: AIITRandomHorizontalFlipPair
    p: 0.5
  - class: AIITRandomVerticalFlipPair
    p: 0.5
  - class: AIITRandomRotationPair
    p: 0.5
    degree: [0, 360]
  - class: AIITResizePair
    size_h: 256
    size_w: 256

test_transforms:  &test_transform
  - class: AIIT2TensorPair
  - class: AIITNormalizePair
    mean: 149.034
    std: 32.022
  - class: AIITMinMaxScaling
    out_range: [0., 255.]
  - class: AIITResizePair
    size_h: 256
    size_w: 256

train_dataset: &train_data
  class: AIITISICDataset
  base_dir: *dir
  transformer:
    class: AIITCompose
    transforms: *train_transform
  train: True

train_dataloader:
  class: AIITDataLoader
  dataset: *train_data
  batch_size: 2
  shuffle: True
  num_workers: 4
  pin_memory: True
  persistent_workers: True


valid_dataset: &valid_data
  class: AIITISICDataset
  base_dir: *dir
  transformer:
    class: AIITCompose
    transforms: *test_transform
  train: False

valid_dataloader:
  class: AIITDataLoader
  dataset: *valid_data
  batch_size: 1
  shuffle: False
  num_workers: 1
  pin_memory: True
  persistent_workers: True

#无test data，test数据集设置为valid_dataset
test_dataset: &test_data
  class: AIITISICDataset
  base_dir: *dir
  transformer:
    class: AIITCompose
    transforms: *test_transform
  train: False

test_dataloader:
  class: AIITDataLoader
  dataset: *test_data
  batch_size: 1
  shuffle: False
  num_workers: 1
  pin_memory: True
  persistent_workers: True
